package com.kie_pract.doo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class foo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.time.LocalDate leaveStartDate;
	private java.lang.String message;
	private java.lang.String leaveType;

	private boolean suffixWeek;

	private boolean prefixweek;

	private boolean suffixHoliday;

	private boolean prefixHoliday;

	private java.time.LocalDate leaveEndDate;

	private int priorDaysPL;

	private int priorDaysCL;

	private int priorDaysLWP;

	private int priorDaysOD;

	private int priorDaysSOD;

	private long leaveCount;

	private java.util.List<java.time.LocalDate> listOfHolidays;

	private boolean reset;

	private java.lang.Boolean betweenHoliday;

	private boolean betweenSunday;

	private int sundays;

	private int count;

	public foo() {
	}

	public java.time.LocalDate getLeaveStartDate() {
		return this.leaveStartDate;
	}

	public void setLeaveStartDate(java.time.LocalDate leaveStartDate) {
		this.leaveStartDate = leaveStartDate;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(java.lang.String leaveType) {
		this.leaveType = leaveType;
	}

	public boolean isSuffixWeek() {
		return this.suffixWeek;
	}

	public void setSuffixWeek(boolean suffixWeek) {
		this.suffixWeek = suffixWeek;
	}

	public boolean isPrefixweek() {
		return this.prefixweek;
	}

	public void setPrefixweek(boolean prefixweek) {
		this.prefixweek = prefixweek;
	}

	public boolean isSuffixHoliday() {
		return this.suffixHoliday;
	}

	public void setSuffixHoliday(boolean suffixHoliday) {
		this.suffixHoliday = suffixHoliday;
	}

	public boolean isPrefixHoliday() {
		return this.prefixHoliday;
	}

	public void setPrefixHoliday(boolean prefixHoliday) {
		this.prefixHoliday = prefixHoliday;
	}

	public java.time.LocalDate getLeaveEndDate() {
		return this.leaveEndDate;
	}

	public void setLeaveEndDate(java.time.LocalDate leaveEndDate) {
		this.leaveEndDate = leaveEndDate;
	}

	public int getPriorDaysPL() {
		return this.priorDaysPL;
	}

	public void setPriorDaysPL(int priorDaysPL) {
		this.priorDaysPL = priorDaysPL;
	}

	public int getPriorDaysCL() {
		return this.priorDaysCL;
	}

	public void setPriorDaysCL(int priorDaysCL) {
		this.priorDaysCL = priorDaysCL;
	}

	public int getPriorDaysLWP() {
		return this.priorDaysLWP;
	}

	public void setPriorDaysLWP(int priorDaysLWP) {
		this.priorDaysLWP = priorDaysLWP;
	}

	public int getPriorDaysOD() {
		return this.priorDaysOD;
	}

	public void setPriorDaysOD(int priorDaysOD) {
		this.priorDaysOD = priorDaysOD;
	}

	public int getPriorDaysSOD() {
		return this.priorDaysSOD;
	}

	public void setPriorDaysSOD(int priorDaysSOD) {
		this.priorDaysSOD = priorDaysSOD;
	}

	public long getLeaveCount() {
		return this.leaveCount;
	}

	public void setLeaveCount(long leaveCount) {
		this.leaveCount = leaveCount;
	}

	public java.util.List<java.time.LocalDate> getListOfHolidays() {
		return this.listOfHolidays;
	}

	public void setListOfHolidays(
			java.util.List<java.time.LocalDate> listOfHolidays) {
		this.listOfHolidays = listOfHolidays;
	}

	public boolean isReset() {
		return this.reset;
	}

	public void setReset(boolean reset) {
		this.reset = reset;
	}

	public java.lang.Boolean getBetweenHoliday() {
		return this.betweenHoliday;
	}

	public void setBetweenHoliday(java.lang.Boolean betweenHoliday) {
		this.betweenHoliday = betweenHoliday;
	}

	public boolean isBetweenSunday() {
		return this.betweenSunday;
	}

	public void setBetweenSunday(boolean betweenSunday) {
		this.betweenSunday = betweenSunday;
	}

	public int getSundays() {
		return this.sundays;
	}

	public void setSundays(int sundays) {
		this.sundays = sundays;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public foo(java.time.LocalDate leaveStartDate, java.lang.String message,
			java.lang.String leaveType, boolean suffixWeek, boolean prefixweek,
			boolean suffixHoliday, boolean prefixHoliday,
			java.time.LocalDate leaveEndDate, int priorDaysPL, int priorDaysCL,
			int priorDaysLWP, int priorDaysOD, int priorDaysSOD,
			long leaveCount,
			java.util.List<java.time.LocalDate> listOfHolidays, boolean reset,
			java.lang.Boolean betweenHoliday, boolean betweenSunday,
			int sundays, int count) {
		this.leaveStartDate = leaveStartDate;
		this.message = message;
		this.leaveType = leaveType;
		this.suffixWeek = suffixWeek;
		this.prefixweek = prefixweek;
		this.suffixHoliday = suffixHoliday;
		this.prefixHoliday = prefixHoliday;
		this.leaveEndDate = leaveEndDate;
		this.priorDaysPL = priorDaysPL;
		this.priorDaysCL = priorDaysCL;
		this.priorDaysLWP = priorDaysLWP;
		this.priorDaysOD = priorDaysOD;
		this.priorDaysSOD = priorDaysSOD;
		this.leaveCount = leaveCount;
		this.listOfHolidays = listOfHolidays;
		this.reset = reset;
		this.betweenHoliday = betweenHoliday;
		this.betweenSunday = betweenSunday;
		this.sundays = sundays;
		this.count = count;
	}

}